version: "3.7"
services:
  redis:
    image: "redis:alpine"
    network_mode: "host"
  backend:
    image: water0641/dudoong-api:0.1.6-1
    container_name: backend
    env_file:
      - .env
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
  front:
    image: david0218/dudoong-ticket:0.0.3-6
    container_name: front
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
  admin:
    image: david0218/dudoong-admin:0.0.2-2
    container_name: admin
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
    # docker build water0641/ticket-nginx-22th:1.0.3 --platform linux/amd64 .
  nginx:
    network_mode: "host"
    depends_on:
      - backend
      - front
      - admin
    restart: always
    image: water0641/dudoong-nginx:1.0.5
    environment:
      - TZ=Asia/Seoul
