version: "3.7"
services:
  redis:
    image: "redis:alpine"
    network_mode: "host"
  backend:
    image: water0641/dudoong-api:2.0.6
    container_name: backend
    env_file:
      - .env
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
  front:
    image: david0218/dudoong-ticket:dev
    container_name: front
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
  admin:
    image: david0218/dudoong-admin:dev
    container_name: admin
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
  internal-admin:
    image: water0641/dudoong-internal-admin:0.2.1
    container_name: internal-admin
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
  nginx:
    network_mode: "host"
    depends_on:
      - backend
      - front
      - admin
      - internal-admin
    restart: always
    image: water0641/dudoong-nginx:1.3.0
    environment:
      - TZ=Asia/Seoul
