FROM nginx:1.30.5
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./proxy_headers.conf /etc/nginx/proxy_headers.conf
COPY ./site.conf /etc/nginx/site.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf
